<?php
/**
 * Thumbnail generator widget
 * Caches the thumbnails to the assets folder
 * If file type is not jpg, png of gif it displays an icon for filetype
 * 
 * Usage:
 * $this->widget('application.components.Thumb', array(
 * 		"imageurl" => $model->filename ,
 * 		"url" =>"media/". $data->category_id. "/" .$data->filename ,
 * 		"alt"=>$model->description,
 * 		"width"=>150,
 * 		"height"=>120,
 * 		"resize"=>Thumb::RESIZE_ADAPTIVE
 * 		)
 * );
 */
 
class Thumb extends CWidget
{   
    const RESIZE_DEFAULT=0;
    const RESIZE_ADAPTIVE=1;
    const RESIZE_CROP=2;
    const RESIZE_CROPCENTER=3;
    
	public $htmlOptions=array();
    public $alt = "";						// The ALT tag of the img element generated by this widget
    public $target = "";                                        // Target attribute of the A tag
    public $imageurl = "";					// The url of the image that should be thumbnailed
    public $url = "";						// The HREF tag of the a element around the image tag
    public $cropX = 0;						// Needed if resize is set to RESIZE_CROP
    public $cropY = 0;						// Needed if resize is set to RESIZE_CROP
    public $width = 100;					// Width of the generated thumbnail
    public $height = 100;					// Height of the generated thumbnail
    public $resize = self::RESIZE_DEFAULT;	// How would you like it to be resized (see const at top of class)
    public $showPopup = true;				// DEPRICATED: need for fancyupload
    public $groupName = 'images';			// The REL tag for the img element
    public $forHTML2PDF = false;			// Nasty hack for html2pdf
    private $mediadir = '/media';			// Where will the thumbnails go? TODO: get from config?

    
	public function run()
	{
        if ($this->imageurl != "")
        {
        	//add / as first char of imageurl if it is not allready there
            if ($this->imageurl[0]!='/') { $this->imageurl = '/'.$this->imageurl; }
            $this->imageurl = str_replace(' ','_',$this->imageurl);
            $src = Yii::getPathOfAlias('webroot').$this->imageurl;
		
            if (!file_exists($src))
            {
             	echo "Cannot find file for thumbnailing! - ".$src;
             	return;
            }

            $pathinfo = pathinfo($src); 
            switch(strtolower($pathinfo['extension']))
            {
            	case 'jpg':
            	case 'gif':
            	case 'png':
            		$this->displayImage($this->createThumb($src));
            		break;
            	case 'mp3':
            	case 'wav':
            	case 'mid':
            	case 'ogg':
            		$this->displayImage("/media/filetypes/sound.png");
            		break;
            	case 'pdf':
            		$this->displayImage("/media/filetypes/pdf.png");
            		break;
            	case 'xls':
            	case 'doc':
            	case 'txt':
            		$this->displayImage("/media/filetypes/document.png");
            		break;
            	case 'wmv':
            	case 'avi':
            	case 'mpg':
            	case 'mov':
            	case 'rm':
            	case 'mkv':
            		$this->displayImage("/media/filetypes/video.png");
            		break;
                case 'dwg':
            		$this->displayImage("/media/filetypes/dwg.png");
            		break;
            	default:
            		$this->displayImage("/media/filetypes/unknown.png");
            		break;
            }
        }
        else
            throw new CException("There is no imageurl provided for the Thumb class");
    }

    
    private function createThumb($src)
    {
        Yii::app()->thumb->setThumbsDirectory('/');

        $pathinfo = pathinfo($this->imageurl);
        $_dirname = $pathinfo['dirname']; 	// Directory of the origional image
        $_ext = $pathinfo['extension'];		// Extension of the image file
        $_filename = $pathinfo['filename'];	// filename of image without extension
        $_thumbfile = $_dirname.'/'.$_filename."_".$this->width.'x'.$this->height.'_'.$this->resize.'.'.$_ext; //Filename of thumb that will be created bv: filename_150x100_1.jpg
        $_thumb = Yii::getPathOfAlias('webroot').$_thumbfile;

        // if not directory for thumb please create, TODO: see if this can be removed
        //if (!is_dir(Yii::getPathOfAlias('webroot').$this->mediadir.$_dirname))
            //mkdir(Yii::getPathOfAlias('webroot').$this->mediadir.$_dirname);

        // if not a thumb please create also check for cache date
        if (!file_exists($_thumb) || (filemtime($_thumb) < @filemtime(Yii::getPathOfAlias('webroot').'/'.$this->imageurl)))
        {
            // make all types of resize possible
            switch($this->resize)
            {
                case self::RESIZE_DEFAULT:
                    Yii::app()->thumb->load($src)->resize($this->width,$this->height)->save($_thumbfile,$_ext);
                    break;
                case self::RESIZE_ADAPTIVE:
                    Yii::app()->thumb->load($src)->adaptiveResize($this->width,$this->height)->save($_thumbfile,$_ext);
                    break;
                case self::RESIZE_CROP:
                    Yii::app()->thumb->load($src)->crop($this->cropX, $this->cropY, $this->width,$this->height)->save($_thumbfile,$_ext);
                    break;
                case self::RESIZE_CROPCENTER:
                    Yii::app()->thumb->load($src)->cropFromCenter($this->width,$this->height)->save($_thumbfile,$_ext);
                    break;
            }
        }
	    return $_thumbfile;
    }
    
    private function displayImage($thumbfile)
    {
    	//No clue what this does apperently its needed
        if (strpos($thumbfile,'./')>-1) $thumbfile = substr($thumbfile,1,strlen($thumbfile)-1);
        
        $backurl = Yii::app()->baseUrl;
        if($this->forHTML2PDF) $backurl = ".";

        if ($this->url != "") { echo CHtml::openTag("a",array("rel"=>$this->groupName, "href"=>$this->url, "title"=>$this->alt, "class"=>"thumbLink", 'target'=>$this->target)); }
        echo CHtml::image($backurl.$thumbfile, $this->alt, $this->htmlOptions);
        if ($this->url != "") { echo CHtml::closeTag("a"); }
    }
}