<?php
/**
 * Message translations.
 *
 * This contains all text from ToolTips in the backend
 *
 * Each new line represents the translation Label => Translation.
 * If the translation is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version: 1.0
 */
return array(

    'meta_title' => '<h2>Title TAG</h2>
        <p>If this field is empty a title for the page will be generated by the system.
        The name of your website will be added to the end of your title on all pages so no need to include that here.
        The contents of the title tag will usually appear in the first line of the results.</p>
        <h2>Accurately describe the page\'s content</h2><strong>Aviod:</strong>
        <ul><li>choosing a title that has no relation to the content on the page</li>
        <li>using default or vague titles like "My homepage" or "News artikel"</li>
        <li>using extremely lengthy titles that are unhelpful to users</li>
        </ul>
        <h2>Create unique title tags for each page</h2>
        <p>Each of your pages should ideally have a unique title tag, 
        which helps Google know how the page is distinct from the others on your site.</p>
        <h2>Use brief, but descriptive titles</h2>
        <p>Titles can be both short and informative. If the title is too long, 
        Google will show only a portion of it in the search result.</p>',
    'meta_description' => '<h2>Meta TAG</h2><p>A page\'s description meta tag gives Google and other search
        engines a summary of what the page is about. Google might use
        them as snippets for your pages.</p>
        <h2>Accurately summarize the page\'s content</h2><p>Write a description that would both inform and interest users if they saw your description meta tag as
        a snippet in a search result.</p><strong>Aviod:</strong>
        <ul><li>writing a description meta tag that has no relation to the content on the page</li>
        <li>using generic descriptions like "This is a web page" or "Page about baseball cards"</li>
        <li>filling the description with only keywords</li>
        <li>copying and pasting the entire content of the document into the description meta tag</li></ul>
        <h2>Use unique descriptions for each page</h2>Having a different description meta tag for each page helps both users and Google, especially in
        searches where users may bring up multiple pages on your domain',
    'meta_keywords' => '<h2>Keywords TAG</h2><p>A page\'s keywords meta tag gives Google and other search
        engines a list of words you can be found on.</p>
        <h2>Keyword need to be comma sepperated</h2><p>You can enter multiple keywords in this field. The different keyword need to be seppertated with a comma.
        Most search engine rely on this kind of formatting</p><strong>Aviod:</strong>
        <ul><li>placing way to many keywords on a page. They will just be ignored anyway</li>
        <li>using the same global keywords for every page like the name of the site</li></ul>
        <h2>Words in your content</h2>Search engines like it if you add some keywords to your metadata. 
        However, the words that are found in the content of your page are worth more so write your content carefully with the search engine in mind.',
    'url_prefix' => '<h2>URL Prefix</h2><p>The word in this textfield gets prepended to the documentname in the URL bar.</p>
        The URL of the webpage may only contain letters [a-z] numbers [0-9] and dashes [-] </p><p>Usually this is the most relevant keyword</p>',
);
?>
